feat: Implementing Github Sign In OAuth
swapnil-musale/GithubCloneApp pull request #1
Opened 2023-03-01 11:56 UTC by swap-musale

2023-03-13 05:47 UTC, pushpalroymm requested changes

2023-03-13 05:47 UTC, pushpalroymm commented on app/src/main/java/com/example/githubcloneapp/util/Constant.kt
> +    const val APP_CLIENT_ID = "8d495907d9bdbe7f5388"
@swap-musale Can we pass these values from Github Secrets? In that way, we don't have to hardcode these.

2023-03-13 05:47 UTC, pushpalroymm commented on domain/src/main/java/com/example/domain/useCase/GetUserInfoUseCase.kt
> +class GetUserInfoUseCase(private val githubRepository: GithubRepository) {
@swap-musale Can we create a BaseUseCase for all use cases?

2023-03-13 05:47 UTC, pushpalroymm commented on domain/src/main/java/com/example/domain/useCase/GetUserAccessToken.kt
> +class GetUserAccessToken(private val githubRepository: GithubRepository) {
@swap-musale Append with UseCase.

2023-03-13 05:47 UTC, pushpalroymm commented on domain/src/main/java/com/example/domain/model/UserInfo.kt
> +    val name: String,
@swap-musale Are all these values coming from server API calls? In that case, shouldn't we make these nullable?

2023-03-14 05:27 UTC, swap-musale commented
closing this  PR Code as it is outdated and same functionality code available in [this PR](https://github.com/swap-musale/GithubCloneApp/pull/2).

2023-03-14 05:27 UTC, closed without merging